module.exports.collateralTypes = [
    'automobile',
    'motorcycle',
    'receivables',
    'investments',
    'machinaryAndEquipment',
    'valuablesAndColletibles',
    'electronicItems',
    'employmentBenefits'
]
module.exports.currentStatus = [
    'depositedIntoBranch',
    'collateralWithBorrower',
    'returnedToBorrower',
    'reposessionInitiated',
    'repossed',
    'underAuction',
    'sold',
    'transferedOwnership',
    'lost',
    'stolen',
    'insuranceClaim'
]
module.exports.useOfFunds = [
    'vehicle',
    'motorcycle',
    'personal',
    'payroll',
    'workingCapital',
    'capitalGoods',
    'refinancing',
    'debtConsolidation',
    'factoring',
    'vehicleWithInsurance',
    'motorcycleWithInsurance',
    'personalWithInsurance',
    'capitalGoodsWithInsurance',
    'creditLine'
]

module.exports.txConcepts = [
    'DEPOSIT',
    'DIVESTMENT',
    'INVESTMENT',
    'WITHDRAWAL',
    'INTERNAL_TRANSFER_RECIPIENT',
    'INTERNAL_TRANSFER_SENDER',
    'INTERNATIONAL_TRANSFER_RECIPIENT',
    'INTERNATIONAL_TRANSFER_SENDER',
    'DIVIDENDS',
    'INTEREST',
    'CAPITAL',
    'FEE',
    'COST',
    'COMMISSION',
    'MANAGEMENT_FEE',
    'MANAGEMENT_INTEREST',
    'INSURANCE_COST',
    'INSURANCE_PREMIUM',
    'BANKING_FEE',
    'BANKING_TRANSFER_FEE',
    'INCOME_ORIGINATION_FEE',
    'COST_ORIGINATION_LEGAL',
    'COST_ORIGINATION_TRANSPORT',
    'COST_ORIGINATION_EXPENSES',
    'COST_ORIGINATION_SENTINEL',
    'COST_SERVICING_LEGAL',
    'COST_SERVICING_TRANSPORT',
    'COST_SERVICING_EXPENSES',
    'SG&A_ACCOUNTING',
    'SG&A_TECH_SERVICES',
    'SG&A_LEGAL',
    'SG&A_MAILING',
    'SG&A_OFFICE_RENT',
    'SG&A_OFFICE_PRINT',
    'SG&A_OFFICE_STORAGE',
    'TRAVEL_EXPENSES',
    'TRANSPORT'
]
module.exports.condition = [
    'new',
    'excellent',
    'good',
    'fair',
    'demaged'
]
module.exports.loanControlStatus = [
    "inReview",
    "approved",
    "denied",
    "open",
    "terminated",
    "paid",
    "canceled",
]
module.exports.loanPaymentStatus = [
    "late",
    "late30",
    "late60",
    "late90",
    "current",
    "defaulted",
    "chargedOff",
]